language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t jaypd/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jaypd/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Docker-react-env-1"
  bucket: "elasticbeanstalk-ap-south-1-720304745538"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key:
    secure: $secret_access_key
